import type { AppSettings, BulkSample } from "./types";

const timestamp = "2026-01-01T00:00:00.000Z";

const visualStyle =
  "Editorial illustration style, bold graphic shapes, limited color palette of navy, gold, and warm gray, textured brush strokes, dark charcoal background,";

const visualEnding =
  "Keep all important text labels, headlines, numbers, and key visual elements above the lower 20% of the frame so they don't conflict with subtitles. The scene extends seamlessly to all four edges with no decorative frame, no painting border, no vignette, no platform or base under main objects. Do not render prompt instructions, format specs, aspect ratio markers, subtitle-safe-area notes, or any production guidance as visible text in the image.";

const fashionVisualStyle =
  "小红书 3:4 竖版时尚编辑风，克制、专业、适合审美解读；使用 mock 视觉素材，不出现真实品牌 logo、真实名人脸、真实媒体截图或版权图片；";

export const initialSettings: AppSettings = {
  output_base_dir: "./mock-outputs",
  auto_poll_enabled: false,
  auto_poll_interval_ms: 5000
};

export const initialSample: BulkSample = {
  ideas: [
    {
      idea_id: "IDEA_XHS_001",
      name: "国际时尚趋势观察：低调奢华之后，为什么“精致实穿”又回来了？",
      tags_json: ["小红书图文", "时尚趋势", "Agent 工作流"],
      detail: "一组模拟的公开作品集示例，用小红书时尚图文场景展示 Hermes Agent 的内容生产结果如何适配 Workflow Sandbox 的 Idea / Scene / Segment / Media Card 格式。",
      created_at: timestamp,
      updated_at: timestamp
    },
    {
      idea_id: "IDEA_001",
      name: "如何把复杂 AI 任务拆成可生产的工作流",
      tags_json: ["AI 工作流", "任务状态机", "生成系统"],
      detail: "一个完全虚构的公开示例，用来展示复杂 AI 任务如何从需求拆解、结构化对象、生成任务推进到结果回写。",
      created_at: timestamp,
      updated_at: timestamp
    }
  ],
  scenes: [
    {
      scene_id: "SCENE_001",
      idea_id: "IDEA_001",
      title: "从需求到结构化任务",
      summary: "先把模糊需求拆成可追踪的对象、字段和检查规则。",
      detail: "这个 scene 展示需求如何进入结构化工作台，成为可保存、可校验、可提交的生产对象。",
      sort_order: 1,
      created_at: timestamp,
      updated_at: timestamp
    },
    {
      scene_id: "SCENE_002",
      idea_id: "IDEA_001",
      title: "从生成任务到结果归档",
      summary: "用 mock provider 演示提交、轮询、失败、重试和预览回写。",
      detail: "这个 scene 展示异步生成任务如何被状态机管理，而不是被一次性请求粗糙处理。",
      sort_order: 2,
      created_at: timestamp,
      updated_at: timestamp
    },
    {
      scene_id: "SCENE_XHS_001",
      idea_id: "IDEA_XHS_001",
      title: "选题与新闻判断",
      summary: "把一组公开时尚信息压缩成适合小红书表达的核心观点。",
      detail: "模拟 Hermes 每日监测后选出的题目：不直接复述新闻，而是提炼一个有审美判断、适合图文表达的观察角度。",
      sort_order: 1,
      created_at: timestamp,
      updated_at: timestamp
    },
    {
      scene_id: "SCENE_XHS_002",
      idea_id: "IDEA_XHS_001",
      title: "视觉证据与历史语境",
      summary: "把当前视觉线索和历史参考拆成可追踪的素材任务。",
      detail: "这个 scene 对齐 Hermes 的 assets/current 与 assets/history：真实运行时放公开新闻图和历史图，公开 demo 中只放 mock 参考图。",
      sort_order: 2,
      created_at: timestamp,
      updated_at: timestamp
    },
    {
      scene_id: "SCENE_XHS_003",
      idea_id: "IDEA_XHS_001",
      title: "小红书成稿与结果回写",
      summary: "把审美判断整理成可发布的图文页，并把 PNG 结果回写到 Media Card。",
      detail: "真实 Hermes 版本会先生成 HTML，再截图成 1080x1440 PNG；Workflow Sandbox 只展示结果和任务状态。",
      sort_order: 3,
      created_at: timestamp,
      updated_at: timestamp
    }
  ],
  segments: [
    {
      segment_id: "SEG_001",
      scene_id: "SCENE_001",
      tab_order: 1,
      title: "明确任务目标",
      summary: "把一句模糊需求改写成可执行目标。",
      narration: "Turn an ambiguous request into an executable goal with clear input, output, and acceptance criteria.",
      narration_cn: "把一句模糊需求改写成可执行目标，先说明输入、输出和验收标准。",
      created_at: timestamp,
      updated_at: timestamp
    },
    {
      segment_id: "SEG_002",
      scene_id: "SCENE_001",
      tab_order: 2,
      title: "设计对象层级",
      summary: "把任务拆成稳定对象和上下游引用。",
      narration: "Break the task into Idea, Scene, Segment, and Media Card objects so every step has stable IDs and references.",
      narration_cn: "把任务拆成 Idea、Scene、Segment 和 Media Card，让每一步都有稳定 ID 和上下游引用。",
      created_at: timestamp,
      updated_at: timestamp
    },
    {
      segment_id: "SEG_003",
      scene_id: "SCENE_002",
      tab_order: 1,
      title: "提交并轮询任务",
      summary: "保存 provider task id，并通过轮询更新任务状态。",
      narration: "Generation requests do not return results immediately, so the system stores provider task IDs and updates task status through polling.",
      narration_cn: "生成请求不会立即得到结果，系统需要保存 provider task id，并通过轮询更新任务状态。",
      created_at: timestamp,
      updated_at: timestamp
    },
    {
      segment_id: "SEG_004",
      scene_id: "SCENE_002",
      tab_order: 2,
      title: "处理失败与重试",
      summary: "记录错误、阻止重复提交，并允许显式重试。",
      narration: "Failure is not the end of the workflow; the system records errors, blocks duplicate submissions, and allows explicit retry.",
      narration_cn: "失败不是流程终点，系统需要记录错误、阻止重复提交，并允许显式重试。",
      created_at: timestamp,
      updated_at: timestamp
    },
    {
      segment_id: "SEG_XHS_001",
      scene_id: "SCENE_XHS_001",
      tab_order: 1,
      title: "封面观点",
      summary: "把今日观察压缩成一个克制但有判断的封面页。",
      narration: "After quiet luxury, the stronger signal is not louder styling, but a return to refined practicality.",
      narration_cn: "低调奢华之后，更值得看的不是更贵的符号，而是“精致实穿”重新变成时尚语言：衣服看起来能进入真实生活，但比例、面料和细节仍然被精确控制。",
      created_at: timestamp,
      updated_at: timestamp
    },
    {
      segment_id: "SEG_XHS_002",
      scene_id: "SCENE_XHS_001",
      tab_order: 2,
      title: "发生了什么",
      summary: "用模拟新闻背景说明这个选题为什么成立。",
      narration: "Recent fashion imagery keeps moving toward useful pieces with sharper proportion and calmer surfaces.",
      narration_cn: "近期的时尚图像里，一个共同变化是：造型不再只追求“看起来高级”，而是更强调能被穿进日常的廓形。夹克、针织、半裙和低饱和配色重新成为叙事主角。",
      created_at: timestamp,
      updated_at: timestamp
    },
    {
      segment_id: "SEG_XHS_003",
      scene_id: "SCENE_XHS_002",
      tab_order: 1,
      title: "视觉关键词",
      summary: "把图片素材拆成几个能被读者识别的视觉线索。",
      narration: "The visual keywords are narrow shoulders, compact bags, softer tailoring, fine knit texture, and low-saturation contrast.",
      narration_cn: "可以抓四个视觉关键词：窄一点的肩线、轻一点的包、软一点的西装、细一点的针织。它们共同制造的是“认真穿衣”，不是用力造型。",
      created_at: timestamp,
      updated_at: timestamp
    },
    {
      segment_id: "SEG_XHS_004",
      scene_id: "SCENE_XHS_002",
      tab_order: 2,
      title: "历史参考",
      summary: "解释历史素材为什么不是简单复古，而是帮助读懂当下。",
      narration: "The historical reference is 1990s minimalism and office dressing, but the current version is lighter and more social-media ready.",
      narration_cn: "它会让人想到 90 年代极简和办公室着装，但今天的版本没有那么冷。它更轻、更柔，也更适合被手机屏幕阅读：重点不是复刻旧时代，而是借用一种“干净的秩序感”。",
      created_at: timestamp,
      updated_at: timestamp
    },
    {
      segment_id: "SEG_XHS_005",
      scene_id: "SCENE_XHS_003",
      tab_order: 1,
      title: "小红书结论",
      summary: "把专业观察收束成适合小红书发布的审美建议。",
      narration: "The practical takeaway is to build polish through proportion and material, not through obvious trend symbols.",
      narration_cn: "普通人可以先理解成一句话：不要急着买一个“趋势单品”，先把衣服的比例、材质和颜色秩序调顺。真正新的地方，是实穿重新变得有审美含量。",
      created_at: timestamp,
      updated_at: timestamp
    }
  ],
  media_cards: [
    {
      media_id: "MEDIA_001",
      segment_id: "SEG_001",
      media_type: "image",
      slot_order: 1,
      prompt: `${visualStyle} an editorial information graphic about transforming a vague AI request into a clear executable goal, a blurred charcoal question shape on the left resolves into three gold-edged task cards representing input, output, and acceptance checks, subtle arrows connect the cards, continuous textured backdrop, screenshot-worthy concept visual, calm decisive mood. ${visualEnding}`,
      reference_images_json: [],
      generate_count: 1,
      provider: "mock-image",
      model: "mock-image-v1",
      duration: null,
      aspect_ratio: "16:9",
      resolution: "1K",
      audio: null,
      aggregate_status: "idle",
      preview_url: null,
      last_error: null,
      last_submitted_at: null,
      created_at: timestamp,
      updated_at: timestamp
    },
    {
      media_id: "MEDIA_002",
      segment_id: "SEG_002",
      media_type: "image",
      slot_order: 1,
      prompt: `${visualStyle} a layered object hierarchy diagram rendered as bold editorial cards, one large gold Idea card branches into two navy Scene cards, each Scene connects to smaller warm gray Segment cards and precise Media Card blocks, clean dependency lines, subtle schema grid texture across the entire canvas, authoritative systems-thinking mood. ${visualEnding}`,
      reference_images_json: [],
      generate_count: 1,
      provider: "mock-image",
      model: "mock-image-v1",
      duration: null,
      aspect_ratio: "16:9",
      resolution: "1K",
      audio: null,
      aggregate_status: "idle",
      preview_url: null,
      last_error: null,
      last_submitted_at: null,
      created_at: timestamp,
      updated_at: timestamp
    },
    {
      media_id: "MEDIA_003",
      segment_id: "SEG_003",
      media_type: "image",
      slot_order: 1,
      prompt: `${visualStyle} an asynchronous generation pipeline shown as a sophisticated timeline, a gold submit node sends task packets into a navy processing lane, two polling ticks update status markers, a completed result card lands in an archive tray, continuous brush texture and faint queue geometry, precise engineering mood. ${visualEnding}`,
      reference_images_json: [],
      generate_count: 1,
      provider: "mock-image",
      model: "mock-image-v1",
      duration: null,
      aspect_ratio: "16:9",
      resolution: "1K",
      audio: null,
      aggregate_status: "idle",
      preview_url: null,
      last_error: null,
      last_submitted_at: null,
      created_at: timestamp,
      updated_at: timestamp
    },
    {
      media_id: "MEDIA_004",
      segment_id: "SEG_004",
      media_type: "image",
      slot_order: 1,
      prompt: `${visualStyle} a retry state machine visual, one failed task card marked by a muted red signal is held behind a guardrail, a deliberate gold retry arrow routes it back through processing, then into a completed archive card, no chaos, no alarmism, just controlled recovery and operational discipline, continuous dark textured backdrop. ${visualEnding}`,
      reference_images_json: [],
      generate_count: 1,
      provider: "mock-image",
      model: "mock-image-v1",
      duration: null,
      aspect_ratio: "16:9",
      resolution: "1K",
      audio: null,
      aggregate_status: "idle",
      preview_url: null,
      last_error: null,
      last_submitted_at: null,
      created_at: timestamp,
      updated_at: timestamp
    },
    {
      media_id: "MEDIA_005",
      segment_id: "SEG_004",
      media_type: "video",
      slot_order: 2,
      prompt: "A short abstract motion sequence: a failed task card pauses behind a guardrail, a deliberate retry arrow sends it back into processing, then it resolves into a completed archive card. Keep the same dark editorial information-graphic style, gold status accents, and controlled operational mood. [FAIL]",
      reference_images_json: [],
      generate_count: 1,
      provider: "mock-video",
      model: "mock-video-v1",
      duration: 6,
      aspect_ratio: "16:9",
      resolution: "720p",
      audio: true,
      aggregate_status: "idle",
      preview_url: null,
      last_error: null,
      last_submitted_at: null,
      created_at: timestamp,
      updated_at: timestamp
    },
    {
      media_id: "MEDIA_XHS_001",
      segment_id: "SEG_XHS_001",
      media_type: "image",
      slot_order: 1,
      prompt: `${fashionVisualStyle}第 1 页封面图。画面需要表达“低调奢华之后，精致实穿重新成为时尚语言”：一组克制的都市廓形、细针织、利落外套和小体量配饰，留出中文标题区域，整体像审美观察，不像带货广告。`,
      reference_images_json: ["/mock-assets/XHS_REF_CURRENT.png"],
      generate_count: 1,
      provider: "mock-image",
      model: "mock-image-v1",
      duration: null,
      aspect_ratio: "3:4",
      resolution: "1080x1440",
      audio: null,
      aggregate_status: "idle",
      preview_url: null,
      last_error: null,
      last_submitted_at: null,
      created_at: timestamp,
      updated_at: timestamp
    },
    {
      media_id: "MEDIA_XHS_002",
      segment_id: "SEG_XHS_002",
      media_type: "image",
      slot_order: 1,
      prompt: `${fashionVisualStyle}第 2 页新闻背景图。用一张虚构的时尚编辑资料板表现“近期时尚图像的共同变化”：秀场笔记、街拍裁片、品牌新闻卡片、低饱和色票；所有元素都为 mock，不使用真实媒体截图。`,
      reference_images_json: ["/mock-assets/XHS_REF_CURRENT.png"],
      generate_count: 1,
      provider: "mock-image",
      model: "mock-image-v1",
      duration: null,
      aspect_ratio: "3:4",
      resolution: "1080x1440",
      audio: null,
      aggregate_status: "idle",
      preview_url: null,
      last_error: null,
      last_submitted_at: null,
      created_at: timestamp,
      updated_at: timestamp
    },
    {
      media_id: "MEDIA_XHS_003",
      segment_id: "SEG_XHS_003",
      media_type: "image",
      slot_order: 1,
      prompt: `${fashionVisualStyle}第 3 页视觉关键词图。把窄肩线、细针织、小体量手袋、柔软西装、低饱和配色做成一张审美证据板，让图片直接服务“精致实穿”的判断。`,
      reference_images_json: ["/mock-assets/XHS_REF_CURRENT.png"],
      generate_count: 1,
      provider: "mock-image",
      model: "mock-image-v1",
      duration: null,
      aspect_ratio: "3:4",
      resolution: "1080x1440",
      audio: null,
      aggregate_status: "idle",
      preview_url: null,
      last_error: null,
      last_submitted_at: null,
      created_at: timestamp,
      updated_at: timestamp
    },
    {
      media_id: "MEDIA_XHS_004",
      segment_id: "SEG_XHS_004",
      media_type: "image",
      slot_order: 1,
      prompt: `${fashionVisualStyle}第 4 页历史语境图。用虚构 archive 氛围表现 90 年代极简与办公室着装的参考关系，但不要复刻真实历史照片；画面要像时间线和风格对照，而不是怀旧海报。`,
      reference_images_json: ["/mock-assets/XHS_REF_HISTORY.png"],
      generate_count: 1,
      provider: "mock-image",
      model: "mock-image-v1",
      duration: null,
      aspect_ratio: "3:4",
      resolution: "1080x1440",
      audio: null,
      aggregate_status: "idle",
      preview_url: null,
      last_error: null,
      last_submitted_at: null,
      created_at: timestamp,
      updated_at: timestamp
    },
    {
      media_id: "MEDIA_XHS_005",
      segment_id: "SEG_XHS_005",
      media_type: "image",
      slot_order: 1,
      prompt: `${fashionVisualStyle}第 5 页结论图。用衣橱网格表达“不要急着买趋势单品，先调顺比例、材质和颜色秩序”：外套、针织、半裙、平底鞋、小包和面料色票，像审美建议，不像购物清单。`,
      reference_images_json: ["/mock-assets/XHS_REF_CURRENT.png", "/mock-assets/XHS_REF_HISTORY.png"],
      generate_count: 1,
      provider: "mock-image",
      model: "mock-image-v1",
      duration: null,
      aspect_ratio: "3:4",
      resolution: "1080x1440",
      audio: null,
      aggregate_status: "idle",
      preview_url: null,
      last_error: null,
      last_submitted_at: null,
      created_at: timestamp,
      updated_at: timestamp
    }
  ],
  covers: [
    {
      cover_id: "COVER_001",
      idea_id: "IDEA_001",
      title: "复杂 AI 任务，应该先被拆成可检查的工作流",
      cover_text: "从需求到任务状态机",
      title_direction: "clarity",
      cover_prompt: `${visualStyle} a complete AI workflow system map, ambiguous request shapes resolve into structured objects, provider tasks, polling ticks, retry loop, and an archive plane, bold graphic shapes and textured brush strokes, senior product-engineering mood.`,
      cover_image_url: "/mock-assets/COVER_001.png",
      generation_status: "completed",
      last_error: null,
      is_active_title: 1,
      is_active_cover: 1,
      sort_order: 1,
      created_at: timestamp,
      updated_at: timestamp
    },
    {
      cover_id: "COVER_002",
      idea_id: "IDEA_001",
      title: "一个 AI 工作台如何管理生成任务的失败与重试",
      cover_text: "异步任务不是一次请求",
      title_direction: "tradeoff",
      cover_prompt: `${visualStyle} a focused state-machine cover visual, task cards move through idle, processing, completed, and failed lanes, a gold retry loop shows controlled recovery, dark editorial information-graphic style.`,
      cover_image_url: "/mock-assets/COVER_002.png",
      generation_status: "completed",
      last_error: null,
      is_active_title: 0,
      is_active_cover: 0,
      sort_order: 2,
      created_at: timestamp,
      updated_at: timestamp
    },
    {
      cover_id: "COVER_XHS_001",
      idea_id: "IDEA_XHS_001",
      title: "低调奢华之后，时尚正在回到“精致实穿”",
      cover_text: "精致实穿回来了",
      title_direction: "clarity",
      cover_prompt: `${fashionVisualStyle}封面候选 1：一张克制的时尚编辑封面，重点突出“精致实穿回来了”，适合直接作为小红书图文第一张。`,
      cover_image_url: "/mock-assets/COVER_XHS_001.png",
      generation_status: "completed",
      last_error: null,
      is_active_title: 1,
      is_active_cover: 1,
      sort_order: 1,
      created_at: timestamp,
      updated_at: timestamp
    },
    {
      cover_id: "COVER_XHS_002",
      idea_id: "IDEA_XHS_001",
      title: "今年的高级感，不是更贵，而是更会穿进日常",
      cover_text: "高级感变实用了",
      title_direction: "tradeoff",
      cover_prompt: `${fashionVisualStyle}封面候选 2：用衣橱细节、比例标注和材质色票表达“高级感变实用了”，作为更偏实用解读的标题方向。`,
      cover_image_url: "/mock-assets/COVER_XHS_002.png",
      generation_status: "completed",
      last_error: null,
      is_active_title: 0,
      is_active_cover: 0,
      sort_order: 2,
      created_at: timestamp,
      updated_at: timestamp
    }
  ]
};
